version: "3"
services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql-db
      DB_PORT: 3306
      DB_DATABASE: liberty_insurance_portal
      DB_USERNAME: root
      DB_PASSWORD: ""

  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: r.7Fqf-)FFnmDa10
      MYSQL_DATABASE: liberty_insurance_portal
      MYSQL_USER: root
      MYSQL_PASSWORD: r.7Fqf-)FFnmDa10
    ports:
      - "3306:3306"
